{ lib, pkgs, ... }:
let
  toastDelivery = "system";
  isWsl =
    pkgs.stdenv.isLinux
    && (builtins.getEnv "WSL_DISTRO_NAME" != "" || builtins.pathExists /run/WSL);

  windowsNotifySend = pkgs.writeShellScriptBin "notify-send" ''
    set -euo pipefail

    if [ "$#" -gt 0 ] && [ "$1" = "--" ]; then
      shift
    fi

    title="''${1-}"
    body="''${2-}"
    if [ -z "$title" ]; then
      exit 2
    fi

    title_b64="$(${pkgs.coreutils}/bin/printf '%s' "$title" | ${pkgs.coreutils}/bin/base64 -w0)"
    body_b64="$(${pkgs.coreutils}/bin/printf '%s' "$body" | ${pkgs.coreutils}/bin/base64 -w0)"
    ps_script=$(cat <<'POWERSHELL'
$ErrorActionPreference = "Stop"
[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
[Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null

$title = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('__TITLE_B64__'))
$body = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('__BODY_B64__'))
$escapedTitle = [System.Security.SecurityElement]::Escape($title)
$escapedBody = [System.Security.SecurityElement]::Escape($body)
$bodyMarkup = if ([string]::IsNullOrEmpty($body)) { "" } else { "<text>$escapedBody</text>" }
$xmlText = "<toast><visual><binding template=""ToastGeneric""><text>$escapedTitle</text>$bodyMarkup</binding></visual></toast>"

$xml = New-Object Windows.Data.Xml.Dom.XmlDocument
$xml.LoadXml($xmlText)
$toast = New-Object Windows.UI.Notifications.ToastNotification $xml
[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe").Show($toast)
POWERSHELL
)
    ps_script="''${ps_script//__TITLE_B64__/$title_b64}"
    ps_script="''${ps_script//__BODY_B64__/$body_b64}"
    encoded="$(${pkgs.coreutils}/bin/printf '%s' "$ps_script" | ${pkgs.glibc.bin}/bin/iconv -f UTF-8 -t UTF-16LE | ${pkgs.coreutils}/bin/base64 -w0)"

    exec powershell.exe -NoLogo -NoProfile -NonInteractive -OutputFormat Text -EncodedCommand "$encoded"
  '';
in
{
  # herdr — agent multiplexer that lives in your terminal
  # https://github.com/ogulcancelik/herdr
  home.packages = with pkgs; [
    herdr
  ] ++ lib.optional isWsl windowsNotifySend;

  # Herdr's system notification backend skips notify-send when both display
  # variables are absent. WSLg normally supplies DISPLAY, but keeping this
  # fallback makes the Windows toast bridge work in plain WSL sessions too.
  home.sessionVariables = lib.mkIf isWsl {
    DISPLAY = ":0";
  };

  xdg.configFile."herdr/config.toml".text = ''
    # herdr configuration — managed by Home Manager
    # Edit in modules/herdr.nix; do not edit this file directly.

    [theme]
    name = "kanagawa"

    [terminal]
    # New panes/tabs/workspaces inherit the source pane's CWD
    # (replaces the former multiplexer CWD binding)
    new_cwd = "follow"

    [keys]
    # Split bindings matching the previous multiplexer config:
    #   / = side-by-side (vertical divider)
    #   - = stacked (horizontal divider)
    split_vertical = "prefix+/"
    split_horizontal = "prefix+-"

    # Free prefix+shift+g for the gh copilot launcher
    new_worktree = ""

    # Tab switching — replaces the former M-Left / M-Right bindings
    # (overrides default prefix+p / prefix+n; use prefix+1..9 for direct access)
    previous_tab = "alt+shift+h"
    next_tab = "alt+shift+l"

    # Workspace switching — replaces the former M-Up / M-Down bindings
    # (were unset by default, so no conflict)
    previous_workspace = "alt+shift+k"
    next_workspace = "alt+shift+j"

    # AI agent launchers (replaces the former popup bindings)
    [[keys.command]]
    key = "prefix+shift+c"
    type = "pane"
    command = "codex -p dotfiles --no-alt-screen"

    [[keys.command]]
    key = "prefix+shift+g"
    type = "pane"
    command = "gh copilot"

    # Direct (no-prefix) pane navigation — replaces the former M-h/j/k/l bindings
    # type = "shell" runs detached; herdr pane focus talks to the server socket
    [[keys.command]]
    key = "alt+h"
    type = "shell"
    command = "herdr pane focus --direction left"

    [[keys.command]]
    key = "alt+j"
    type = "shell"
    command = "herdr pane focus --direction down"

    [[keys.command]]
    key = "alt+k"
    type = "shell"
    command = "herdr pane focus --direction up"

    [[keys.command]]
    key = "alt+l"
    type = "shell"
    command = "herdr pane focus --direction right"

    [session]
    # Resume AI-agent panes into their native sessions after a server restart
    resume_agents_on_restore = true

    [ui]
    # Show agent labels in split pane borders
    show_agent_labels_on_pane_borders = true

    [ui.toast]
    # Ghostty suppresses OSC notifications while focused. Use the system
    # backend so completion notifications remain available in that case.
    delivery = "${toastDelivery}"
    delay_seconds = 15
  '';
  xdg.configFile."herdr/config.toml".force = true;

  # Keep Herdr's agent integrations installed after Home Manager activation.
  # The commands are idempotent and update the generated hook files/settings
  # when Herdr changes its integration assets.
  home.activation.herdrIntegrations = lib.hm.dag.entryAfter [ "writeBoundary" "installPackages" ] ''
    for integration in codex copilot; do
      ${pkgs.herdr}/bin/herdr integration install "$integration" >/dev/null
    done
  '';
}
