{ lib, pkgs, ... }:
{
  # herdr — agent multiplexer that lives in your terminal
  # https://github.com/ogulcancelik/herdr
  home.packages = with pkgs; [
    herdr
    # Keep tmux installed for the tmux skill (programmatic terminal
    # control via send-keys / capture-pane). herdr replaces tmux as
    # the daily-driver multiplexer, but the skill still needs the binary.
    tmux
  ];

  xdg.configFile."herdr/config.toml".text = ''
    # herdr configuration — managed by Home Manager
    # Edit in modules/herdr.nix; do not edit this file directly.

    [theme]
    name = "tokyo-night"

    [terminal]
    # New panes/tabs/workspaces inherit the source pane's CWD
    # (replaces tmux's -c "#{pane_current_path}")
    new_cwd = "follow"

    [keys]
    # Split bindings matching the previous tmux config:
    #   / = side-by-side (vertical divider)
    #   - = stacked (horizontal divider)
    split_vertical = "prefix+/"
    split_horizontal = "prefix+-"

    # Free prefix+shift+g for the gh copilot launcher
    new_worktree = ""

    # Tab switching — replaces tmux M-Left / M-Right
    # (overrides default prefix+p / prefix+n; use prefix+1..9 for direct access)
    previous_tab = "alt+shift+h"
    next_tab = "alt+shift+l"

    # Workspace switching — replaces tmux M-Up / M-Down (switch-client)
    # (were unset by default, so no conflict)
    previous_workspace = "alt+shift+k"
    next_workspace = "alt+shift+j"

    # AI agent launchers (replaces tmux display-popup bindings)
    [[keys.command]]
    key = "prefix+shift+c"
    type = "pane"
    command = "codex -p dotfiles --no-alt-screen"

    [[keys.command]]
    key = "prefix+shift+g"
    type = "pane"
    command = "gh copilot"

    # Direct (no-prefix) pane navigation — replaces tmux bind -n M-h/j/k/l
    # type = "shell" runs detached; herdr pane focus talks to the server socket
    [[keys.command]]
    key = "alt+h"
    type = "shell"
    command = "herdr pane focus --direction left"

    [[keys.command]]
    key = "alt+j"
    type = "shell"
    command = "herdr pane focus --direction down"

    [[keys.command]]
    key = "alt+k"
    type = "shell"
    command = "herdr pane focus --direction up"

    [[keys.command]]
    key = "alt+l"
    type = "shell"
    command = "herdr pane focus --direction right"

    [session]
    # Resume AI-agent panes into their native sessions after a server restart
    resume_agents_on_restore = true

    [ui]
    # Show agent labels in split pane borders
    show_agent_labels_on_pane_borders = true
  '';
  xdg.configFile."herdr/config.toml".force = true;

  # Keep Herdr's agent integrations installed after Home Manager activation.
  # The commands are idempotent and update the generated hook files/settings
  # when Herdr changes its integration assets.
  home.activation.herdrIntegrations = lib.hm.dag.entryAfter [ "writeBoundary" "installPackages" ] ''
    for integration in codex copilot; do
      ${pkgs.herdr}/bin/herdr integration install "$integration" >/dev/null
    done
  '';
}
